version: '3'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    container_name: laravel-mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
